# Generated by Django 4.2.1 on 2023-06-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flower", "0001_initial"),
    ]

    operations = []
