# Generated by Django 4.2.1 on 2023-06-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flower", "0002_auto_20230612_1008"),
    ]

    operations = []
