# Generated by Django 4.2.1 on 2023-06-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flower", "0003_auto_20230612_1012"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="fifth_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="image",
            name="fifth_value",
            field=models.FloatField(default=0),
        ),
    ]
